[
    {
        "category": "CONFIG",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ASDS0030",
        "result.error.detailedDescription": "Configuration of this protection policy cannot be completed because an error occurred on the application agent host.",
        "result.error.extendedReason": null,
        "result.error.reason": "Unable to configure the policy because of an error on the application agent.",
        "result.error.remediation": "To resolve this issue:\n1. Delete the files in the following directories:\nOn Windows, \\INSTALL_DIR\\AGENTSERVICECONFIG.\nOn Linux and AIX, /opt/dpsapps/agentsvc/config.\n2. In the PowerProtect Data Manager UI, go to Protection > Protection Policies, select this policy, and click Set Lockbox.\nIf the issue persists, contact Dell Customer Support.",
        "asset.name": "Mailbox Database 0597205983",
        "asset.type": "MICROSOFT_EXCHANGE_DATABASE",
        "host.name": "exchange.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-13T11:50:23.278Z",
        "endTime": "2024-11-13T11:50:26.238Z"
    },
    {
        "category": "CONFIG",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABV0025",
        "result.error.detailedDescription": "The VM Direct engine cannot complete protection of this virtual machine because the protection configuration was unsuccessful.",
        "result.error.extendedReason": "Unable to configure protection for the asset because SCSI sharing and is not supported.",
        "result.error.reason": "VM Direct engine is unable to configure protection for the virtual machine 'win-11' on vCenter 'VCenter'.",
        "result.error.remediation": "Review the error details and summary log in the Jobs window, or export the job logs and review the log files for more information. If the issue persists, contact Dell Customer Support.",
        "asset.name": "win-11",
        "asset.type": "VMWARE_VIRTUAL_MACHINE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "VCENTER",
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": "VMWARE_VIRTUAL_MACHINE",
        "createTime": "2024-11-13T11:52:12.829Z",
        "endTime": "2024-11-13T11:52:32.884Z"
    },
    {
        "category": "CONFIG",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABV0025",
        "result.error.detailedDescription": "The VM Direct engine cannot complete protection of this virtual machine because the protection configuration was unsuccessful.",
        "result.error.extendedReason": "Unable to configure protection for the asset because SCSI sharing and is not supported.",
        "result.error.reason": "VM Direct engine is unable to configure protection for the virtual machine 'win-10' on vCenter 'VCenter'.",
        "result.error.remediation": "Review the error details and summary log in the Jobs window, or export the job logs and review the log files for more information. If the issue persists, contact Dell Customer Support.",
        "asset.name": "win-10",
        "asset.type": "VMWARE_VIRTUAL_MACHINE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "VCENTER",
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": "VMWARE_VIRTUAL_MACHINE",
        "createTime": "2024-11-13T11:52:17.091Z",
        "endTime": "2024-11-13T11:52:33.050Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABNA0020",
        "result.error.detailedDescription": "The existence of the target asset cannot be validated.",
        "result.error.extendedReason": "NAS vProxy Engine nas-proxy.demo.local is unable to perform SnapshotAndSlice operation for nasShare /ifs/data/csi/k8s-33b51b73dd. \n\nError Details:\n TaskId: 18236d26-48d0-4cf0-9810-9dd397c08fb6, JobId 18236d26-48d0-4cf0-9810-9dd397c08fb6 \n NAS agent error code 'ABNA0020'. Unable to complete the 'SNAPSHOT_AND_SLICE' operation because the location for asset '/ifs/data/csi/k8s-33b51b73dd' could not be validated in PowerScale/Isilon NAS '192.168.1.108'.. \n",
        "result.error.reason": "Unable to complete a SNAPSHOT_AND_SLICE operation because the location for asset /ifs/data/csi/k8s-33b51b73dd could not be validated in PowerScale/Isilon NAS 192.168.1.108.",
        "result.error.remediation": "Connect to the PowerScale/Isilon NAS and verify that the share exists. \nFrom the PowerProtect Data Manager Asset Source page, perform an on-demand discovery of assets from this asset source.",
        "asset.name": null,
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-13T11:51:35.182Z",
        "endTime": "2024-11-13T11:53:19.571Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "SKIPPED",
        "result.error.code": "AERR0004",
        "result.error.detailedDescription": "This task cannot be completed when dependent protection tasks do not complete successfully.",
        "result.error.extendedReason": null,
        "result.error.reason": "Task Performing data rollover for the slices created was skipped because the protection task was unsuccessful.",
        "result.error.remediation": "Review the details for the protection task in the Jobs window to troubleshoot the issue. When the issue is resolved, retry the protection job task. If the issue persists, contact Dell Customer Support.",
        "asset.name": null,
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-13T11:51:35.204Z",
        "endTime": "2024-11-13T11:53:19.695Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABNA0020",
        "result.error.detailedDescription": "The existence of the target asset cannot be validated.",
        "result.error.extendedReason": "NAS vProxy Engine nas-proxy.demo.local is unable to perform SnapshotAndSlice operation for nasShare /ifs/data/csi/k8s-33b51b73dd. \n\nError Details:\n TaskId: 18236d26-48d0-4cf0-9810-9dd397c08fb6, JobId 18236d26-48d0-4cf0-9810-9dd397c08fb6 \n NAS agent error code 'ABNA0020'. Unable to complete the 'SNAPSHOT_AND_SLICE' operation because the location for asset '/ifs/data/csi/k8s-33b51b73dd' could not be validated in PowerScale/Isilon NAS '192.168.1.108'.. \n",
        "result.error.reason": "Unable to complete a SNAPSHOT_AND_SLICE operation because the location for asset /ifs/data/csi/k8s-33b51b73dd could not be validated in PowerScale/Isilon NAS 192.168.1.108.",
        "result.error.remediation": "Connect to the PowerScale/Isilon NAS and verify that the share exists. \nFrom the PowerProtect Data Manager Asset Source page, perform an on-demand discovery of assets from this asset source.",
        "asset.name": "/ifs/data/csi/k8s-33b51b73dd",
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-13T11:51:35.162Z",
        "endTime": "2024-11-13T11:53:55.500Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "SKIPPED",
        "result.error.code": "AERR0004",
        "result.error.detailedDescription": "This task cannot be completed when dependent protection tasks do not complete successfully.",
        "result.error.extendedReason": null,
        "result.error.reason": "Task Performing data rollover for the slices created was skipped because the protection task was unsuccessful.",
        "result.error.remediation": "Review the details for the protection task in the Jobs window to troubleshoot the issue. When the issue is resolved, retry the protection job task. If the issue persists, contact Dell Customer Support.",
        "asset.name": null,
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-13T11:51:35.347Z",
        "endTime": "2024-11-13T11:54:22.571Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABNA0020",
        "result.error.detailedDescription": "The existence of the target asset cannot be validated.",
        "result.error.extendedReason": "NAS vProxy Engine nas-proxy.demo.local is unable to perform SnapshotAndSlice operation for nasShare /ifs/data/csi/k8s-0aa9eb47f2. \n\nError Details:\n TaskId: 75842c05-2947-4e05-85fe-7c00e0db9362, JobId 75842c05-2947-4e05-85fe-7c00e0db9362 \n NAS agent error code 'ABNA0020'. Unable to complete the 'SNAPSHOT_AND_SLICE' operation because the location for asset '/ifs/data/csi/k8s-0aa9eb47f2' could not be validated in PowerScale/Isilon NAS '192.168.1.108'.. \n",
        "result.error.reason": "Unable to complete a SNAPSHOT_AND_SLICE operation because the location for asset /ifs/data/csi/k8s-0aa9eb47f2 could not be validated in PowerScale/Isilon NAS 192.168.1.108.",
        "result.error.remediation": "Connect to the PowerScale/Isilon NAS and verify that the share exists. \nFrom the PowerProtect Data Manager Asset Source page, perform an on-demand discovery of assets from this asset source.",
        "asset.name": null,
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-13T11:51:35.329Z",
        "endTime": "2024-11-13T11:54:22.460Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABNA0020",
        "result.error.detailedDescription": "The existence of the target asset cannot be validated.",
        "result.error.extendedReason": "NAS vProxy Engine nas-proxy.demo.local is unable to perform SnapshotAndSlice operation for nasShare /ifs/data/csi/k8s-0aa9eb47f2. \n\nError Details:\n TaskId: 75842c05-2947-4e05-85fe-7c00e0db9362, JobId 75842c05-2947-4e05-85fe-7c00e0db9362 \n NAS agent error code 'ABNA0020'. Unable to complete the 'SNAPSHOT_AND_SLICE' operation because the location for asset '/ifs/data/csi/k8s-0aa9eb47f2' could not be validated in PowerScale/Isilon NAS '192.168.1.108'.. \n",
        "result.error.reason": "Unable to complete a SNAPSHOT_AND_SLICE operation because the location for asset /ifs/data/csi/k8s-0aa9eb47f2 could not be validated in PowerScale/Isilon NAS 192.168.1.108.",
        "result.error.remediation": "Connect to the PowerScale/Isilon NAS and verify that the share exists. \nFrom the PowerProtect Data Manager Asset Source page, perform an on-demand discovery of assets from this asset source.",
        "asset.name": "/ifs/data/csi/k8s-0aa9eb47f2",
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-13T11:51:35.310Z",
        "endTime": "2024-11-13T11:54:50.448Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABNA0020",
        "result.error.detailedDescription": "The existence of the target asset cannot be validated.",
        "result.error.extendedReason": "NAS vProxy Engine nas-proxy.demo.local is unable to perform SnapshotAndSlice operation for nasShare /ifs/data/csi/k8s-d8196857f7. \n\nError Details:\n TaskId: aeb5aba1-8f7e-4135-8e25-29e5b5330a49, JobId aeb5aba1-8f7e-4135-8e25-29e5b5330a49 \n NAS agent error code 'ABNA0020'. Unable to complete the 'SNAPSHOT_AND_SLICE' operation because the location for asset '/ifs/data/csi/k8s-d8196857f7' could not be validated in PowerScale/Isilon NAS '192.168.1.108'.. \n",
        "result.error.reason": "Unable to complete a SNAPSHOT_AND_SLICE operation because the location for asset /ifs/data/csi/k8s-d8196857f7 could not be validated in PowerScale/Isilon NAS 192.168.1.108.",
        "result.error.remediation": "Connect to the PowerScale/Isilon NAS and verify that the share exists. \nFrom the PowerProtect Data Manager Asset Source page, perform an on-demand discovery of assets from this asset source.",
        "asset.name": null,
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-13T11:51:35.634Z",
        "endTime": "2024-11-13T11:57:31.601Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "SKIPPED",
        "result.error.code": "AERR0004",
        "result.error.detailedDescription": "This task cannot be completed when dependent protection tasks do not complete successfully.",
        "result.error.extendedReason": null,
        "result.error.reason": "Task Performing data rollover for the slices created was skipped because the protection task was unsuccessful.",
        "result.error.remediation": "Review the details for the protection task in the Jobs window to troubleshoot the issue. When the issue is resolved, retry the protection job task. If the issue persists, contact Dell Customer Support.",
        "asset.name": null,
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-13T11:51:35.656Z",
        "endTime": "2024-11-13T11:57:31.757Z"
    },
    {
        "category": "CONFIG",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ASDS0030",
        "result.error.detailedDescription": "Configuration of this protection policy cannot be completed because an error occurred on the application agent host.",
        "result.error.extendedReason": null,
        "result.error.reason": "Unable to configure the policy because of an error on the application agent.",
        "result.error.remediation": "To resolve this issue:\n1. Delete the files in the following directories:\nOn Windows, \\INSTALL_DIR\\AGENTSERVICECONFIG.\nOn Linux and AIX, /opt/dpsapps/agentsvc/config.\n2. In the PowerProtect Data Manager UI, go to Protection > Protection Policies, select this policy, and click Set Lockbox.\nIf the issue persists, contact Dell Customer Support.",
        "asset.name": "Test_DB_002",
        "asset.type": "MICROSOFT_EXCHANGE_DATABASE",
        "host.name": "exchange.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-13T11:50:23.393Z",
        "endTime": "2024-11-13T11:50:26.248Z"
    },
    {
        "category": "CONFIG",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ASDS0030",
        "result.error.detailedDescription": "Configuration of this protection policy cannot be completed because an error occurred on the application agent host.",
        "result.error.extendedReason": null,
        "result.error.reason": "Unable to configure the policy because of an error on the application agent.",
        "result.error.remediation": "To resolve this issue:\n1. Delete the files in the following directories:\nOn Windows, \\INSTALL_DIR\\AGENTSERVICECONFIG.\nOn Linux and AIX, /opt/dpsapps/agentsvc/config.\n2. In the PowerProtect Data Manager UI, go to Protection > Protection Policies, select this policy, and click Set Lockbox.\nIf the issue persists, contact Dell Customer Support.",
        "asset.name": "Test_DB_003",
        "asset.type": "MICROSOFT_EXCHANGE_DATABASE",
        "host.name": "exchange.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": "MICROSOFT_EXCHANGE_DATABASE",
        "createTime": "2024-11-13T11:50:18.613Z",
        "endTime": "2024-11-13T11:50:27.489Z"
    },
    {
        "category": "CONFIG",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ASDS0030",
        "result.error.detailedDescription": "Configuration of this protection policy cannot be completed because an error occurred on the application agent host.",
        "result.error.extendedReason": null,
        "result.error.reason": "Unable to configure the policy because of an error on the application agent.",
        "result.error.remediation": "To resolve this issue:\n1. Delete the files in the following directories:\nOn Windows, \\INSTALL_DIR\\AGENTSERVICECONFIG.\nOn Linux and AIX, /opt/dpsapps/agentsvc/config.\n2. In the PowerProtect Data Manager UI, go to Protection > Protection Policies, select this policy, and click Set Lockbox.\nIf the issue persists, contact Dell Customer Support.",
        "asset.name": "Test_DB_003",
        "asset.type": "MICROSOFT_EXCHANGE_DATABASE",
        "host.name": "exchange.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-13T11:50:23.345Z",
        "endTime": "2024-11-13T11:50:26.243Z"
    },
    {
        "category": "CONFIG",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ASDS0030",
        "result.error.detailedDescription": "Configuration of this protection policy cannot be completed because an error occurred on the application agent host.",
        "result.error.extendedReason": null,
        "result.error.reason": "Unable to configure the policy because of an error on the application agent.",
        "result.error.remediation": "To resolve this issue:\n1. Delete the files in the following directories:\nOn Windows, \\INSTALL_DIR\\AGENTSERVICECONFIG.\nOn Linux and AIX, /opt/dpsapps/agentsvc/config.\n2. In the PowerProtect Data Manager UI, go to Protection > Protection Policies, select this policy, and click Set Lockbox.\nIf the issue persists, contact Dell Customer Support.",
        "asset.name": "Test_DB_001",
        "asset.type": "MICROSOFT_EXCHANGE_DATABASE",
        "host.name": "exchange.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": "MICROSOFT_EXCHANGE_DATABASE",
        "createTime": "2024-11-13T11:50:18.324Z",
        "endTime": "2024-11-13T11:50:26.973Z"
    },
    {
        "category": "CONFIG",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ASDS0030",
        "result.error.detailedDescription": "Configuration of this protection policy cannot be completed because an error occurred on the application agent host.",
        "result.error.extendedReason": null,
        "result.error.reason": "Unable to configure the policy because of an error on the application agent.",
        "result.error.remediation": "To resolve this issue:\n1. Delete the files in the following directories:\nOn Windows, \\INSTALL_DIR\\AGENTSERVICECONFIG.\nOn Linux and AIX, /opt/dpsapps/agentsvc/config.\n2. In the PowerProtect Data Manager UI, go to Protection > Protection Policies, select this policy, and click Set Lockbox.\nIf the issue persists, contact Dell Customer Support.",
        "asset.name": "Mailbox Database 0597205983",
        "asset.type": "MICROSOFT_EXCHANGE_DATABASE",
        "host.name": "exchange.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": "MICROSOFT_EXCHANGE_DATABASE",
        "createTime": "2024-11-13T11:50:18.486Z",
        "endTime": "2024-11-13T11:50:28.083Z"
    },
    {
        "category": "CONFIG",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ASDS0030",
        "result.error.detailedDescription": "Configuration of this protection policy cannot be completed because an error occurred on the application agent host.",
        "result.error.extendedReason": null,
        "result.error.reason": "Unable to configure the policy because of an error on the application agent.",
        "result.error.remediation": "To resolve this issue:\n1. Delete the files in the following directories:\nOn Windows, \\INSTALL_DIR\\AGENTSERVICECONFIG.\nOn Linux and AIX, /opt/dpsapps/agentsvc/config.\n2. In the PowerProtect Data Manager UI, go to Protection > Protection Policies, select this policy, and click Set Lockbox.\nIf the issue persists, contact Dell Customer Support.",
        "asset.name": "Test_DB_002",
        "asset.type": "MICROSOFT_EXCHANGE_DATABASE",
        "host.name": "exchange.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": "MICROSOFT_EXCHANGE_DATABASE",
        "createTime": "2024-11-13T11:50:18.770Z",
        "endTime": "2024-11-13T11:50:27.798Z"
    },
    {
        "category": "CONFIG",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ASDS0030",
        "result.error.detailedDescription": "Configuration of this protection policy cannot be completed because an error occurred on the application agent host.",
        "result.error.extendedReason": null,
        "result.error.reason": "Unable to configure the policy because of an error on the application agent.",
        "result.error.remediation": "To resolve this issue:\n1. Delete the files in the following directories:\nOn Windows, \\INSTALL_DIR\\AGENTSERVICECONFIG.\nOn Linux and AIX, /opt/dpsapps/agentsvc/config.\n2. In the PowerProtect Data Manager UI, go to Protection > Protection Policies, select this policy, and click Set Lockbox.\nIf the issue persists, contact Dell Customer Support.",
        "asset.name": "Test_DB_001",
        "asset.type": "MICROSOFT_EXCHANGE_DATABASE",
        "host.name": "exchange.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-13T11:50:23.185Z",
        "endTime": "2024-11-13T11:50:26.209Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "UNKNOWN",
        "result.error.code": "ABA0023",
        "result.error.detailedDescription": "Monitoring of this session cannot be completed because of an unknown error occurred during monitoring.",
        "result.error.extendedReason": "",
        "result.error.reason": "Exchange Backups - TEST PLC: Unable to monitor backup/restore session of MICROSOFT_EXCHANGE_DATABASE asset Mailbox Database 0597205983 in host exchange.demo.local because of an unknown error. The backup/restore session might be running on the client.",
        "result.error.remediation": "Monitor the next few jobs and please ensure network connectivity between agent and PowerProtect Data Manager has no issues and all the services of PowerProtect Data Manager are up and running.",
        "asset.name": "Mailbox Database 0597205983",
        "asset.type": null,
        "host.name": "exchange.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-13T11:50:53.429Z",
        "endTime": "2024-11-13T11:50:57.587Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "UNKNOWN",
        "result.error.code": "ABA0023",
        "result.error.detailedDescription": "Monitoring of this session cannot be completed because of an unknown error occurred during monitoring.",
        "result.error.extendedReason": "",
        "result.error.reason": "Exchange Backups - TEST PLC: Unable to monitor backup/restore session of MICROSOFT_EXCHANGE_DATABASE asset Test_DB_002 in host exchange.demo.local because of an unknown error. The backup/restore session might be running on the client.",
        "result.error.remediation": "Monitor the next few jobs and please ensure network connectivity between agent and PowerProtect Data Manager has no issues and all the services of PowerProtect Data Manager are up and running.",
        "asset.name": "Test_DB_002",
        "asset.type": null,
        "host.name": "exchange.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-13T11:50:53.413Z",
        "endTime": "2024-11-13T11:50:57.599Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "UNKNOWN",
        "result.error.code": "ABA0023",
        "result.error.detailedDescription": "Monitoring of this session cannot be completed because of an unknown error occurred during monitoring.",
        "result.error.extendedReason": "",
        "result.error.reason": "Exchange Backups - TEST PLC: Unable to monitor backup/restore session of MICROSOFT_EXCHANGE_DATABASE asset Test_DB_004 in host exchange.demo.local because of an unknown error. The backup/restore session might be running on the client.",
        "result.error.remediation": "Monitor the next few jobs and please ensure network connectivity between agent and PowerProtect Data Manager has no issues and all the services of PowerProtect Data Manager are up and running.",
        "asset.name": "Test_DB_004",
        "asset.type": null,
        "host.name": "exchange.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-13T11:50:53.407Z",
        "endTime": "2024-11-13T11:50:57.603Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "UNKNOWN",
        "result.error.code": "ABA0023",
        "result.error.detailedDescription": "Monitoring of this session cannot be completed because of an unknown error occurred during monitoring.",
        "result.error.extendedReason": "",
        "result.error.reason": "Exchange Backups - TEST PLC: Unable to monitor backup/restore session of MICROSOFT_EXCHANGE_DATABASE asset Test_DB_003 in host exchange.demo.local because of an unknown error. The backup/restore session might be running on the client.",
        "result.error.remediation": "Monitor the next few jobs and please ensure network connectivity between agent and PowerProtect Data Manager has no issues and all the services of PowerProtect Data Manager are up and running.",
        "asset.name": "Test_DB_003",
        "asset.type": null,
        "host.name": "exchange.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-13T11:50:53.417Z",
        "endTime": "2024-11-13T11:50:57.606Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "UNKNOWN",
        "result.error.code": "ABA0023",
        "result.error.detailedDescription": "Monitoring of this session cannot be completed because of an unknown error occurred during monitoring.",
        "result.error.extendedReason": "",
        "result.error.reason": "Exchange Backups - TEST PLC: Unable to monitor backup/restore session of MICROSOFT_EXCHANGE_DATABASE asset Test_DB_001 in host exchange.demo.local because of an unknown error. The backup/restore session might be running on the client.",
        "result.error.remediation": "Monitor the next few jobs and please ensure network connectivity between agent and PowerProtect Data Manager has no issues and all the services of PowerProtect Data Manager are up and running.",
        "asset.name": "Test_DB_001",
        "asset.type": null,
        "host.name": "exchange.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-13T11:50:53.418Z",
        "endTime": "2024-11-13T11:50:57.609Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "UNKNOWN",
        "result.error.code": "ABA0023",
        "result.error.detailedDescription": "Monitoring of this session cannot be completed because of an unknown error occurred during monitoring.",
        "result.error.extendedReason": "",
        "result.error.reason": "Exchange Backups - TEST PLC: Unable to monitor backup/restore session of MICROSOFT_EXCHANGE_DATABASE asset Mailbox Database 0597205983 in host exchange.demo.local because of an unknown error. The backup/restore session might be running on the client.",
        "result.error.remediation": "Monitor the next few jobs and please ensure network connectivity between agent and PowerProtect Data Manager has no issues and all the services of PowerProtect Data Manager are up and running.",
        "asset.name": "Mailbox Database 0597205983",
        "asset.type": "MICROSOFT_EXCHANGE_DATABASE",
        "host.name": "exchange.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": "MICROSOFT_EXCHANGE_DATABASE",
        "createTime": "2024-11-13T11:50:23.649Z",
        "endTime": "2024-11-13T11:50:58.080Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "UNKNOWN",
        "result.error.code": "ABA0023",
        "result.error.detailedDescription": "Monitoring of this session cannot be completed because of an unknown error occurred during monitoring.",
        "result.error.extendedReason": "",
        "result.error.reason": "Exchange Backups - TEST PLC: Unable to monitor backup/restore session of MICROSOFT_EXCHANGE_DATABASE asset Test_DB_003 in host exchange.demo.local because of an unknown error. The backup/restore session might be running on the client.",
        "result.error.remediation": "Monitor the next few jobs and please ensure network connectivity between agent and PowerProtect Data Manager has no issues and all the services of PowerProtect Data Manager are up and running.",
        "asset.name": "Test_DB_003",
        "asset.type": "MICROSOFT_EXCHANGE_DATABASE",
        "host.name": "exchange.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": "MICROSOFT_EXCHANGE_DATABASE",
        "createTime": "2024-11-13T11:50:24.470Z",
        "endTime": "2024-11-13T11:50:57.949Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "UNKNOWN",
        "result.error.code": "ABA0023",
        "result.error.detailedDescription": "Monitoring of this session cannot be completed because of an unknown error occurred during monitoring.",
        "result.error.extendedReason": "",
        "result.error.reason": "Exchange Backups - TEST PLC: Unable to monitor backup/restore session of MICROSOFT_EXCHANGE_DATABASE asset Test_DB_004 in host exchange.demo.local because of an unknown error. The backup/restore session might be running on the client.",
        "result.error.remediation": "Monitor the next few jobs and please ensure network connectivity between agent and PowerProtect Data Manager has no issues and all the services of PowerProtect Data Manager are up and running.",
        "asset.name": "Test_DB_004",
        "asset.type": "MICROSOFT_EXCHANGE_DATABASE",
        "host.name": "exchange.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": "MICROSOFT_EXCHANGE_DATABASE",
        "createTime": "2024-11-13T11:50:23.469Z",
        "endTime": "2024-11-13T11:50:58.184Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "UNKNOWN",
        "result.error.code": "ABA0023",
        "result.error.detailedDescription": "Monitoring of this session cannot be completed because of an unknown error occurred during monitoring.",
        "result.error.extendedReason": "",
        "result.error.reason": "Exchange Backups - TEST PLC: Unable to monitor backup/restore session of MICROSOFT_EXCHANGE_DATABASE asset Test_DB_002 in host exchange.demo.local because of an unknown error. The backup/restore session might be running on the client.",
        "result.error.remediation": "Monitor the next few jobs and please ensure network connectivity between agent and PowerProtect Data Manager has no issues and all the services of PowerProtect Data Manager are up and running.",
        "asset.name": "Test_DB_002",
        "asset.type": "MICROSOFT_EXCHANGE_DATABASE",
        "host.name": "exchange.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": "MICROSOFT_EXCHANGE_DATABASE",
        "createTime": "2024-11-13T11:50:23.899Z",
        "endTime": "2024-11-13T11:50:57.892Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "UNKNOWN",
        "result.error.code": "ABA0023",
        "result.error.detailedDescription": "Monitoring of this session cannot be completed because of an unknown error occurred during monitoring.",
        "result.error.extendedReason": "",
        "result.error.reason": "Exchange Backups - TEST PLC: Unable to monitor backup/restore session of MICROSOFT_EXCHANGE_DATABASE asset Test_DB_001 in host exchange.demo.local because of an unknown error. The backup/restore session might be running on the client.",
        "result.error.remediation": "Monitor the next few jobs and please ensure network connectivity between agent and PowerProtect Data Manager has no issues and all the services of PowerProtect Data Manager are up and running.",
        "asset.name": "Test_DB_001",
        "asset.type": "MICROSOFT_EXCHANGE_DATABASE",
        "host.name": "exchange.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Exchange Backups - TEST PLC",
        "protectionPolicy.type": "MICROSOFT_EXCHANGE_DATABASE",
        "createTime": "2024-11-13T11:50:24.205Z",
        "endTime": "2024-11-13T11:50:58.304Z"
    },
    {
        "category": "CONFIG",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABV0025",
        "result.error.detailedDescription": "The VM Direct engine cannot complete protection of this virtual machine because the protection configuration was unsuccessful.",
        "result.error.extendedReason": "Unable to configure protection for the asset because SCSI sharing and is not supported.",
        "result.error.reason": "VM Direct engine is unable to configure protection for the virtual machine 'win-11' on vCenter 'VCenter'.",
        "result.error.remediation": "Review the error details and summary log in the Jobs window, or export the job logs and review the log files for more information. If the issue persists, contact Dell Customer Support.",
        "asset.name": "win-11",
        "asset.type": null,
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-13T11:52:30.184Z",
        "endTime": "2024-11-13T11:52:31.192Z"
    },
    {
        "category": "CONFIG",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABV0025",
        "result.error.detailedDescription": "The VM Direct engine cannot complete protection of this virtual machine because the protection configuration was unsuccessful.",
        "result.error.extendedReason": "Unable to configure protection for the asset because SCSI sharing and is not supported.",
        "result.error.reason": "VM Direct engine is unable to configure protection for the virtual machine 'win-10' on vCenter 'VCenter'.",
        "result.error.remediation": "Review the error details and summary log in the Jobs window, or export the job logs and review the log files for more information. If the issue persists, contact Dell Customer Support.",
        "asset.name": "win-10",
        "asset.type": null,
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-13T11:52:30.768Z",
        "endTime": "2024-11-13T11:52:31.742Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABNA0020",
        "result.error.detailedDescription": "The existence of the target asset cannot be validated.",
        "result.error.extendedReason": "NAS vProxy Engine nas-proxy.demo.local is unable to perform SnapshotAndSlice operation for nasShare /ifs/data/csi/k8s-418144021c. \n\nError Details:\n TaskId: fdadbb74-4db8-403c-a048-483a921f2a1d, JobId fdadbb74-4db8-403c-a048-483a921f2a1d \n NAS agent error code 'ABNA0020'. Unable to complete the 'SNAPSHOT_AND_SLICE' operation because the location for asset '/ifs/data/csi/k8s-418144021c' could not be validated in PowerScale/Isilon NAS '192.168.1.108'.. \n",
        "result.error.reason": "Unable to complete a SNAPSHOT_AND_SLICE operation because the location for asset /ifs/data/csi/k8s-418144021c could not be validated in PowerScale/Isilon NAS 192.168.1.108.",
        "result.error.remediation": "Connect to the PowerScale/Isilon NAS and verify that the share exists. \nFrom the PowerProtect Data Manager Asset Source page, perform an on-demand discovery of assets from this asset source.",
        "asset.name": null,
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-13T11:51:35.471Z",
        "endTime": "2024-11-13T11:55:58.116Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "SKIPPED",
        "result.error.code": "AERR0004",
        "result.error.detailedDescription": "This task cannot be completed when dependent protection tasks do not complete successfully.",
        "result.error.extendedReason": null,
        "result.error.reason": "Task Performing data rollover for the slices created was skipped because the protection task was unsuccessful.",
        "result.error.remediation": "Review the details for the protection task in the Jobs window to troubleshoot the issue. When the issue is resolved, retry the protection job task. If the issue persists, contact Dell Customer Support.",
        "asset.name": null,
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-13T11:51:35.489Z",
        "endTime": "2024-11-13T11:55:58.202Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABNA0020",
        "result.error.detailedDescription": "The existence of the target asset cannot be validated.",
        "result.error.extendedReason": "NAS vProxy Engine nas-proxy.demo.local is unable to perform SnapshotAndSlice operation for nasShare /ifs/data/csi/k8s-418144021c. \n\nError Details:\n TaskId: fdadbb74-4db8-403c-a048-483a921f2a1d, JobId fdadbb74-4db8-403c-a048-483a921f2a1d \n NAS agent error code 'ABNA0020'. Unable to complete the 'SNAPSHOT_AND_SLICE' operation because the location for asset '/ifs/data/csi/k8s-418144021c' could not be validated in PowerScale/Isilon NAS '192.168.1.108'.. \n",
        "result.error.reason": "Unable to complete a SNAPSHOT_AND_SLICE operation because the location for asset /ifs/data/csi/k8s-418144021c could not be validated in PowerScale/Isilon NAS 192.168.1.108.",
        "result.error.remediation": "Connect to the PowerScale/Isilon NAS and verify that the share exists. \nFrom the PowerProtect Data Manager Asset Source page, perform an on-demand discovery of assets from this asset source.",
        "asset.name": "/ifs/data/csi/k8s-418144021c",
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-13T11:51:35.449Z",
        "endTime": "2024-11-13T11:56:25.897Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABNA0020",
        "result.error.detailedDescription": "The existence of the target asset cannot be validated.",
        "result.error.extendedReason": "NAS vProxy Engine nas-proxy.demo.local is unable to perform SnapshotAndSlice operation for nasShare /ifs/data/csi/k8s-d8196857f7. \n\nError Details:\n TaskId: aeb5aba1-8f7e-4135-8e25-29e5b5330a49, JobId aeb5aba1-8f7e-4135-8e25-29e5b5330a49 \n NAS agent error code 'ABNA0020'. Unable to complete the 'SNAPSHOT_AND_SLICE' operation because the location for asset '/ifs/data/csi/k8s-d8196857f7' could not be validated in PowerScale/Isilon NAS '192.168.1.108'.. \n",
        "result.error.reason": "Unable to complete a SNAPSHOT_AND_SLICE operation because the location for asset /ifs/data/csi/k8s-d8196857f7 could not be validated in PowerScale/Isilon NAS 192.168.1.108.",
        "result.error.remediation": "Connect to the PowerScale/Isilon NAS and verify that the share exists. \nFrom the PowerProtect Data Manager Asset Source page, perform an on-demand discovery of assets from this asset source.",
        "asset.name": "/ifs/data/csi/k8s-d8196857f7",
        "asset.type": "NAS_SHARE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "NAS Backups - TEST PLC",
        "protectionPolicy.type": "NAS_SHARE",
        "createTime": "2024-11-13T11:51:35.599Z",
        "endTime": "2024-11-13T11:57:58.757Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABV0016",
        "result.error.detailedDescription": "The VM Direct engine cannot complete the backup of this virtual machine because a vCenter API operation did not complete successfully.",
        "result.error.extendedReason": "Unable to successfully complete SDM Full Sync operation.  The error cannot be retried.  The vCenter task for 'SDM Snapshot Sync Full' completed with state 'error'.  TSDM Error Code: <FileCloneError>, TSDM Error Message: <Protected entity file clone error. Error message: Failed to clone file [sourceFilePath='PLCTLP-526629ba-5227-4c6f-a26d-0ff368976ef4/Stagings/4c6e8a0d-b323-44bf-b12b-da850be18bc5/502f3a1b-c525-c168-d635-458eb6542c7e/1731499477744857928/fullSyncTmp/vm-30-disk-key-2000-flat.vmdk', targetFilePath='PLCTLP-526629ba-5227-4c6f-a26d-0ff368976ef4/StagingsSDM/4c6e8a0d-b323-44bf-b12b-da850be18bc5/502f3a1b-c525-c168-d635-458eb6542c7e/attempt_vm-30-disk-key-2000-flat.vmdk', status='nothing matched']>.",
        "result.error.reason": "VM Direct engine 'localhost' is unable to back up the virtual machine 'Exchange' on vCenter 'VCenter' because of a vCenter API issue.",
        "result.error.remediation": "To troubleshoot this issue: 1) Verify that the vCenter can be reached. 2) If the vCenter is busy, wait for some activities to complete and then retry the operation. 3) Verify that the virtual machine exists on the vCenter.",
        "asset.name": "Exchange",
        "asset.type": "VMWARE_VIRTUAL_MACHINE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "VCENTER",
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": "VMWARE_VIRTUAL_MACHINE",
        "createTime": "2024-11-13T11:52:19.101Z",
        "endTime": "2024-11-13T12:05:42.401Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABV0009",
        "result.error.detailedDescription": "The VM Direct engine cannot complete the backup of this virtual machine because the protection storage operation was unsuccessful.",
        "result.error.extendedReason": "Backup has FAILED.  Unable to backup virtual disk \"Hard disk 1\".  Write data.  Unsuccessful writing at offset 22908239872 of data file:  [5175] Out of space",
        "result.error.reason": "VM Direct engine 'localhost' is unable to back up the virtual machine 'k8-master01' on vCenter 'VCenter' because of a protection storage issue.",
        "result.error.remediation": "To resolve this issue: 1) Verify that the PowerProtect DD is functional and that the DD Boost ports are open. 2) Check the network connection between the VM Direct engine 'localhost' and the PowerProtect DD.",
        "asset.name": "k8-master01",
        "asset.type": "VMWARE_VIRTUAL_MACHINE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "VCENTER",
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": "VMWARE_VIRTUAL_MACHINE",
        "createTime": "2024-11-13T11:52:17.728Z",
        "endTime": "2024-11-13T12:05:42.401Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABV0016",
        "result.error.detailedDescription": "The VM Direct engine cannot complete the backup of this virtual machine because a vCenter API operation did not complete successfully.",
        "result.error.extendedReason": "Unable to successfully complete SDM Full Sync operation.  The error cannot be retried.  The vCenter task for 'SDM Snapshot Sync Full' completed with state 'error'.  TSDM Error Code: <FileCloneError>, TSDM Error Message: <Protected entity file clone error. Error message: Failed to clone file [sourceFilePath='PLCTLP-526629ba-5227-4c6f-a26d-0ff368976ef4/Stagings/4c6e8a0d-b323-44bf-b12b-da850be18bc5/502f3a1b-c525-c168-d635-458eb6542c7e/1731499477744857928/fullSyncTmp/vm-30-disk-key-2000-flat.vmdk', targetFilePath='PLCTLP-526629ba-5227-4c6f-a26d-0ff368976ef4/StagingsSDM/4c6e8a0d-b323-44bf-b12b-da850be18bc5/502f3a1b-c525-c168-d635-458eb6542c7e/attempt_vm-30-disk-key-2000-flat.vmdk', status='nothing matched']>.",
        "result.error.reason": "VM Direct engine 'localhost' is unable to back up the virtual machine 'Exchange' on vCenter 'VCenter' because of a vCenter API issue.",
        "result.error.remediation": "To troubleshoot this issue: 1) Verify that the vCenter can be reached. 2) If the vCenter is busy, wait for some activities to complete and then retry the operation. 3) Verify that the virtual machine exists on the vCenter.",
        "asset.name": "Exchange",
        "asset.type": null,
        "host.name": "esxi03-7.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-13T11:54:13.273Z",
        "endTime": "2024-11-13T12:05:41.949Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABV0009",
        "result.error.detailedDescription": "The VM Direct engine cannot complete the backup of this virtual machine because the protection storage operation was unsuccessful.",
        "result.error.extendedReason": "Backup has FAILED.  Unable to backup virtual disk \"Hard disk 1\".  Write data.  Unsuccessful writing at offset 22908239872 of data file:  [5175] Out of space",
        "result.error.reason": "VM Direct engine 'localhost' is unable to back up the virtual machine 'k8-master01' on vCenter 'VCenter' because of a protection storage issue.",
        "result.error.remediation": "To resolve this issue: 1) Verify that the PowerProtect DD is functional and that the DD Boost ports are open. 2) Check the network connection between the VM Direct engine 'localhost' and the PowerProtect DD.",
        "asset.name": "k8-master01",
        "asset.type": null,
        "host.name": "esxi01-7.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-13T11:58:57.113Z",
        "endTime": "2024-11-13T12:05:41.934Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABV0026",
        "result.error.detailedDescription": "The VM Direct engine cannot complete the backup of this virtual machine because of a protection storage capacity issue on the PowerProtect DD.",
        "result.error.extendedReason": "Cannot create export directory 'Virtual_Machines_-Crash_consistent_--ppdm-01-ef2c3/PLCTLP-526629ba-5227-4c6f-a26d-0ff368976ef4/Stagings/4c6e8a0d-b323-44bf-b12b-da850be18bc5/501f1b61-1a78-75a2-de97-6d802f87a084/1731499571663019131' on 'ddve-01.demo.local':  [5005] No space left on device",
        "result.error.reason": "The VM Direct engine 'localhost' is unable to back up the virtual machine 'PPDM-01' on vCenter 'VCenter' because the available space on the protection storage system 'ddve-01.demo.local' is insufficient.",
        "result.error.remediation": "Check the protection storage system to determine if there is enough free space for the operation. The PowerProtect DD Administration Guide provides more information on how to reclaim space.",
        "asset.name": "PPDM-01",
        "asset.type": null,
        "host.name": "esxi01-7.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-13T12:06:09.609Z",
        "endTime": "2024-11-13T12:06:15.585Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABV0016",
        "result.error.detailedDescription": "The VM Direct engine cannot complete the backup of this virtual machine because a vCenter API operation did not complete successfully.",
        "result.error.extendedReason": "Unable to successfully complete SDM Full Sync operation.  The error cannot be retried.  The vCenter task for 'SDM Snapshot Sync Full' completed with state 'error'.  TSDM Error Code: <FileCloneError>, TSDM Error Message: <Protected entity file clone error. Error message: Failed to clone file [sourceFilePath='PLCTLP-526629ba-5227-4c6f-a26d-0ff368976ef4/Stagings/4c6e8a0d-b323-44bf-b12b-da850be18bc5/52798cf3-8550-686b-9b30-3ad738e468a6/1731499477775801795/fullSyncTmp/vm-43-disk-key-2009-flat.vmdk', targetFilePath='PLCTLP-526629ba-5227-4c6f-a26d-0ff368976ef4/StagingsSDM/4c6e8a0d-b323-44bf-b12b-da850be18bc5/52798cf3-8550-686b-9b30-3ad738e468a6/attempt_vm-43-disk-key-2009-flat.vmdk', status='nothing matched']>.",
        "result.error.reason": "VM Direct engine 'localhost' is unable to back up the virtual machine 'VMware vCenter Server' on vCenter 'VCenter' because of a vCenter API issue.",
        "result.error.remediation": "To troubleshoot this issue: 1) Verify that the vCenter can be reached. 2) If the vCenter is busy, wait for some activities to complete and then retry the operation. 3) Verify that the virtual machine exists on the vCenter.",
        "asset.name": "VMware vCenter Server",
        "asset.type": "VMWARE_VIRTUAL_MACHINE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "VCENTER",
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": "VMWARE_VIRTUAL_MACHINE",
        "createTime": "2024-11-13T11:52:19.416Z",
        "endTime": "2024-11-13T12:06:12.306Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "AERR0019",
        "result.error.detailedDescription": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.extendedReason": null,
        "result.error.reason": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.remediation": "To troubleshoot this issue: wait for some time and then retry the operation again. If the issue persists, contact Dell Customer Support.",
        "asset.name": "PPDM-01",
        "asset.type": "VMWARE_VIRTUAL_MACHINE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "VCENTER",
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": "VMWARE_VIRTUAL_MACHINE",
        "createTime": "2024-11-13T11:52:17.995Z",
        "endTime": "2024-11-13T12:06:15.826Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABV0016",
        "result.error.detailedDescription": "The VM Direct engine cannot complete the backup of this virtual machine because a vCenter API operation did not complete successfully.",
        "result.error.extendedReason": "Unable to successfully complete SDM Full Sync operation.  The error cannot be retried.  The vCenter task for 'SDM Snapshot Sync Full' completed with state 'error'.  TSDM Error Code: <FileCloneError>, TSDM Error Message: <Protected entity file clone error. Error message: Failed to clone file [sourceFilePath='PLCTLP-526629ba-5227-4c6f-a26d-0ff368976ef4/Stagings/4c6e8a0d-b323-44bf-b12b-da850be18bc5/52798cf3-8550-686b-9b30-3ad738e468a6/1731499477775801795/fullSyncTmp/vm-43-disk-key-2009-flat.vmdk', targetFilePath='PLCTLP-526629ba-5227-4c6f-a26d-0ff368976ef4/StagingsSDM/4c6e8a0d-b323-44bf-b12b-da850be18bc5/52798cf3-8550-686b-9b30-3ad738e468a6/attempt_vm-43-disk-key-2009-flat.vmdk', status='nothing matched']>.",
        "result.error.reason": "VM Direct engine 'localhost' is unable to back up the virtual machine 'VMware vCenter Server' on vCenter 'VCenter' because of a vCenter API issue.",
        "result.error.remediation": "To troubleshoot this issue: 1) Verify that the vCenter can be reached. 2) If the vCenter is busy, wait for some activities to complete and then retry the operation. 3) Verify that the virtual machine exists on the vCenter.",
        "asset.name": "VMware vCenter Server",
        "asset.type": null,
        "host.name": "esxi03-7.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-13T11:54:13.643Z",
        "endTime": "2024-11-13T12:06:12.002Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABV0026",
        "result.error.detailedDescription": "The VM Direct engine cannot complete the backup of this virtual machine because of a protection storage capacity issue on the PowerProtect DD.",
        "result.error.extendedReason": "Cannot create export directory 'Virtual_Machines_-Crash_consistent_--ppdm-01-ef2c3/PLCTLP-526629ba-5227-4c6f-a26d-0ff368976ef4/Stagings/4c6e8a0d-b323-44bf-b12b-da850be18bc5/501ff233-101a-7719-e1a6-5f0964cdd7e8/1731499603682011521' on 'ddve-01.demo.local':  [5005] No space left on device",
        "result.error.reason": "The VM Direct engine 'localhost' is unable to back up the virtual machine 'k8-node01' on vCenter 'VCenter' because the available space on the protection storage system 'ddve-01.demo.local' is insufficient.",
        "result.error.remediation": "Check the protection storage system to determine if there is enough free space for the operation. The PowerProtect DD Administration Guide provides more information on how to reclaim space.",
        "asset.name": "k8-node01",
        "asset.type": null,
        "host.name": "esxi01-7.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-13T12:06:40.794Z",
        "endTime": "2024-11-13T12:06:47.587Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "AERR0019",
        "result.error.detailedDescription": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.extendedReason": null,
        "result.error.reason": "This task is unsuccessful because internal issue happens at service side.",
        "result.error.remediation": "To troubleshoot this issue: wait for some time and then retry the operation again. If the issue persists, contact Dell Customer Support.",
        "asset.name": "k8-node01",
        "asset.type": "VMWARE_VIRTUAL_MACHINE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "VCENTER",
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": "VMWARE_VIRTUAL_MACHINE",
        "createTime": "2024-11-13T11:52:18.404Z",
        "endTime": "2024-11-13T12:06:48.122Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABV0025",
        "result.error.detailedDescription": "The VM Direct engine cannot complete protection of this virtual machine because the protection configuration was unsuccessful.",
        "result.error.extendedReason": "Unable to configure protection for the asset because SCSI sharing and is not supported.",
        "result.error.reason": "VM Direct engine is unable to configure protection for the virtual machine 'win-10' on vCenter 'VCenter'.",
        "result.error.remediation": "Review the error details and summary log in the Jobs window, or export the job logs and review the log files for more information. If the issue persists, contact Dell Customer Support.",
        "asset.name": "win-10",
        "asset.type": "VMWARE_VIRTUAL_MACHINE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "VCENTER",
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": "VMWARE_VIRTUAL_MACHINE",
        "createTime": "2024-11-13T11:52:18.541Z",
        "endTime": "2024-11-13T12:07:11.902Z"
    },
    {
        "category": "CONFIG",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABV0025",
        "result.error.detailedDescription": "The VM Direct engine cannot complete protection of this virtual machine because the protection configuration was unsuccessful.",
        "result.error.extendedReason": "Unable to configure protection for the asset because SCSI sharing and is not supported.",
        "result.error.reason": "VM Direct engine is unable to configure protection for the virtual machine 'win-10' on vCenter 'VCenter'.",
        "result.error.remediation": "Review the error details and summary log in the Jobs window, or export the job logs and review the log files for more information. If the issue persists, contact Dell Customer Support.",
        "asset.name": "win-10",
        "asset.type": null,
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-13T12:07:11.232Z",
        "endTime": "2024-11-13T12:07:11.505Z"
    },
    {
        "category": "CONFIG",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABV0025",
        "result.error.detailedDescription": "The VM Direct engine cannot complete protection of this virtual machine because the protection configuration was unsuccessful.",
        "result.error.extendedReason": "Unable to configure protection for the asset because SCSI sharing and is not supported.",
        "result.error.reason": "VM Direct engine is unable to configure protection for the virtual machine 'win-11' on vCenter 'VCenter'.",
        "result.error.remediation": "Review the error details and summary log in the Jobs window, or export the job logs and review the log files for more information. If the issue persists, contact Dell Customer Support.",
        "asset.name": "win-11",
        "asset.type": null,
        "host.name": null,
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-13T12:07:41.841Z",
        "endTime": "2024-11-13T12:07:42.079Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABV0025",
        "result.error.detailedDescription": "The VM Direct engine cannot complete protection of this virtual machine because the protection configuration was unsuccessful.",
        "result.error.extendedReason": "Unable to configure protection for the asset because SCSI sharing and is not supported.",
        "result.error.reason": "VM Direct engine is unable to configure protection for the virtual machine 'win-11' on vCenter 'VCenter'.",
        "result.error.remediation": "Review the error details and summary log in the Jobs window, or export the job logs and review the log files for more information. If the issue persists, contact Dell Customer Support.",
        "asset.name": "win-11",
        "asset.type": "VMWARE_VIRTUAL_MACHINE",
        "host.name": null,
        "host.type": null,
        "inventorySource.type": "VCENTER",
        "protectionPolicy.name": "Virtual Machines -Crash consistent -Test PLC",
        "protectionPolicy.type": "VMWARE_VIRTUAL_MACHINE",
        "createTime": "2024-11-13T11:52:18.830Z",
        "endTime": "2024-11-13T12:07:42.503Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABF0001",
        "result.error.detailedDescription": "The backup for this asset cannot be completed because an error occurred.",
        "result.error.extendedReason": "",
        "result.error.reason": "Unable to protect the asset C:\\ on the host win-01.demo.local from the backup performed at time 1/1/1970 12:00:00 AM because the following error occurred: Unable to perform block-based backup for saveset: C:\\..",
        "result.error.remediation": "Click export log, check the export logs from PowerProtect Data Manager and review the log file for more details. If the issue persists, contact Dell Customer Support.",
        "asset.name": "C:\\",
        "asset.type": null,
        "host.name": "win-01.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-13T11:50:53.413Z",
        "endTime": "2024-11-13T12:16:31.236Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABF0001",
        "result.error.detailedDescription": "The backup for this asset cannot be completed because an error occurred.",
        "result.error.extendedReason": "",
        "result.error.reason": "Unable to protect the asset C:\\ on the host win-01.demo.local from the backup performed at time 1/1/1970 12:00:00 AM because the following error occurred: Unable to perform block-based backup for saveset: C:\\..",
        "result.error.remediation": "Click export log, check the export logs from PowerProtect Data Manager and review the log file for more details. If the issue persists, contact Dell Customer Support.",
        "asset.name": "C:\\",
        "asset.type": "FILE_SYSTEM",
        "host.name": "win-01.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": "FILE_SYSTEM",
        "createTime": "2024-11-13T11:50:48.619Z",
        "endTime": "2024-11-13T12:16:31.477Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABF0001",
        "result.error.detailedDescription": "The backup for this asset cannot be completed because an error occurred.",
        "result.error.extendedReason": "",
        "result.error.reason": "Unable to protect the asset DISASTER_RECOVERY:\\ on the host win-11.demo.local from the backup performed at time 1731498994 because the following error occurred: DD write failure result code: 5175, description: Out of space.",
        "result.error.remediation": "Click export log, check the export logs from PowerProtect Data Manager and review the log file for more details. If the issue persists, contact Dell Customer Support.",
        "asset.name": "DISASTER_RECOVERY:\\",
        "asset.type": null,
        "host.name": "win-11.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-13T11:56:19.933Z",
        "endTime": "2024-11-13T12:20:01.036Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABF0001",
        "result.error.detailedDescription": "The backup for this asset cannot be completed because an error occurred.",
        "result.error.extendedReason": "",
        "result.error.reason": "Unable to protect the asset DISASTER_RECOVERY:\\ on the host win-11.demo.local from the backup performed at time 1731498994 because the following error occurred: DD write failure result code: 5175, description: Out of space.",
        "result.error.remediation": "Click export log, check the export logs from PowerProtect Data Manager and review the log file for more details. If the issue persists, contact Dell Customer Support.",
        "asset.name": "DISASTER_RECOVERY:\\",
        "asset.type": "FILE_SYSTEM",
        "host.name": "win-11.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": "FILE_SYSTEM",
        "createTime": "2024-11-13T11:50:49.099Z",
        "endTime": "2024-11-13T12:20:01.188Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABF0001",
        "result.error.detailedDescription": "The backup for this asset cannot be completed because an error occurred.",
        "result.error.extendedReason": "",
        "result.error.reason": "Unable to protect the asset DISASTER_RECOVERY:\\ on the host win-10.demo.local from the backup performed at time 1731498671 because the following error occurred: DD write failure result code: 5175, description: Out of space.",
        "result.error.remediation": "Click export log, check the export logs from PowerProtect Data Manager and review the log file for more details. If the issue persists, contact Dell Customer Support.",
        "asset.name": "DISASTER_RECOVERY:\\",
        "asset.type": null,
        "host.name": "win-10.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-13T11:50:53.463Z",
        "endTime": "2024-11-13T12:20:30.843Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABF0001",
        "result.error.detailedDescription": "The backup for this asset cannot be completed because an error occurred.",
        "result.error.extendedReason": "",
        "result.error.reason": "Unable to protect the asset DISASTER_RECOVERY:\\ on the host win-10.demo.local from the backup performed at time 1731498671 because the following error occurred: DD write failure result code: 5175, description: Out of space.",
        "result.error.remediation": "Click export log, check the export logs from PowerProtect Data Manager and review the log file for more details. If the issue persists, contact Dell Customer Support.",
        "asset.name": "DISASTER_RECOVERY:\\",
        "asset.type": "FILE_SYSTEM",
        "host.name": "win-10.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": "FILE_SYSTEM",
        "createTime": "2024-11-13T11:50:48.782Z",
        "endTime": "2024-11-13T12:20:30.950Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: SQLite database initialization failed.",
        "result.error.reason": "Filesystem Backups -TEST PLC: Unable to backup FILE_SYSTEM asset DISASTER_RECOVERY:\\ on host win-01.demo.local to storage target Filesystem_Backups_-TEST_PLC-ppdm-01-b89b3 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "DISASTER_RECOVERY:\\",
        "asset.type": "FILE_SYSTEM",
        "host.name": "win-01.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": "FILE_SYSTEM",
        "createTime": "2024-11-13T11:50:48.472Z",
        "endTime": "2024-11-13T12:27:31.118Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: SQLite database initialization failed.",
        "result.error.reason": "Filesystem Backups -TEST PLC: Unable to backup FILE_SYSTEM asset DISASTER_RECOVERY:\\ on host win-01.demo.local to storage target Filesystem_Backups_-TEST_PLC-ppdm-01-b89b3 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "DISASTER_RECOVERY:\\",
        "asset.type": null,
        "host.name": "win-01.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-13T12:16:50.274Z",
        "endTime": "2024-11-13T12:27:30.964Z"
    },
    {
        "category": "PROTECT",
        "classType": "TASK",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: SQLite database initialization failed.",
        "result.error.reason": "Filesystem Backups -TEST PLC: Unable to backup FILE_SYSTEM asset C:\\ on host win-10.demo.local to storage target Filesystem_Backups_-TEST_PLC-ppdm-01-b89b3 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "C:\\",
        "asset.type": null,
        "host.name": "win-10.demo.local",
        "host.type": null,
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": null,
        "createTime": "2024-11-13T12:20:53.779Z",
        "endTime": "2024-11-13T12:31:31.454Z"
    },
    {
        "category": "PROTECT",
        "classType": "JOB",
        "result.status": "FAILED",
        "result.error.code": "ABA0002",
        "result.error.detailedDescription": "The protection policy backup was unsuccessful because of an agent issue.",
        "result.error.extendedReason": "Protection policy backup was unsuccessful because the Agent failed with the following error: SQLite database initialization failed.",
        "result.error.reason": "Filesystem Backups -TEST PLC: Unable to backup FILE_SYSTEM asset C:\\ on host win-10.demo.local to storage target Filesystem_Backups_-TEST_PLC-ppdm-01-b89b3 because of an agent issue.",
        "result.error.remediation": "Click export log and review the log file to determine the status of the job or check agent logs for more details.",
        "asset.name": "C:\\",
        "asset.type": "FILE_SYSTEM",
        "host.name": "win-10.demo.local",
        "host.type": "APP_HOST",
        "inventorySource.type": null,
        "protectionPolicy.name": "Filesystem Backups -TEST PLC",
        "protectionPolicy.type": "FILE_SYSTEM",
        "createTime": "2024-11-13T11:50:48.937Z",
        "endTime": "2024-11-13T12:31:31.802Z"
    }
]